"""empty message

Revision ID: 6e4dd970a1bc
Revises: 
Create Date: 2019-12-11 11:39:04.263218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4dd970a1bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_date'), 'availability', ['date'], unique=False)
    op.create_index(op.f('ix_availability_end_time'), 'availability', ['end_time'], unique=False)
    op.create_index(op.f('ix_availability_start_time'), 'availability', ['start_time'], unique=False)
    op.create_index(op.f('ix_availability_user'), 'availability', ['user'], unique=False)
    op.create_table('mechanic__ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mechanic', sa.String(), nullable=True),
    sa.Column('average', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechanic__ratings_average'), 'mechanic__ratings', ['average'], unique=False)
    op.create_index(op.f('ix_mechanic__ratings_mechanic'), 'mechanic__ratings', ['mechanic'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('Tire_rotations', sa.String(), nullable=True),
    sa.Column('Registration_update', sa.String(), nullable=True),
    sa.Column('Change_break', sa.String(), nullable=True),
    sa.Column('Car_Wash', sa.String(), nullable=True),
    sa.Column('Oil_change', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_Car_Wash'), 'recommendations', ['Car_Wash'], unique=False)
    op.create_index(op.f('ix_recommendations_Change_break'), 'recommendations', ['Change_break'], unique=False)
    op.create_index(op.f('ix_recommendations_Oil_change'), 'recommendations', ['Oil_change'], unique=False)
    op.create_index(op.f('ix_recommendations_Registration_update'), 'recommendations', ['Registration_update'], unique=False)
    op.create_index(op.f('ix_recommendations_Tire_rotations'), 'recommendations', ['Tire_rotations'], unique=False)
    op.create_index(op.f('ix_recommendations_user'), 'recommendations', ['user'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mechanic', sa.String(), nullable=True),
    sa.Column('rating', sa.DECIMAL(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_comment'), 'reviews', ['comment'], unique=False)
    op.create_index(op.f('ix_reviews_mechanic'), 'reviews', ['mechanic'], unique=False)
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_reviews_user'), 'reviews', ['user'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=20), nullable=True),
    sa.Column('vehicle', sa.String(), nullable=True),
    sa.Column('mechanic', sa.String(), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=True),
    sa.Column('appointment_time', sa.Time(), nullable=True),
    sa.Column('appointment_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_appointment_date'), 'schedules', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_schedules_appointment_time'), 'schedules', ['appointment_time'], unique=False)
    op.create_index(op.f('ix_schedules_appointment_type'), 'schedules', ['appointment_type'], unique=False)
    op.create_index(op.f('ix_schedules_mechanic'), 'schedules', ['mechanic'], unique=False)
    op.create_index(op.f('ix_schedules_status'), 'schedules', ['status'], unique=False)
    op.create_index(op.f('ix_schedules_user'), 'schedules', ['user'], unique=False)
    op.create_index(op.f('ix_schedules_vehicle'), 'schedules', ['vehicle'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_user'), 'user', ['user'], unique=True)
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=16), nullable=True),
    sa.Column('car_vin', sa.String(length=16), nullable=True),
    sa.Column('make', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('miles_until_oil_change', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_car_vin'), 'car', ['car_vin'], unique=True)
    op.create_index(op.f('ix_car_color'), 'car', ['color'], unique=False)
    op.create_index(op.f('ix_car_make'), 'car', ['make'], unique=False)
    op.create_index(op.f('ix_car_mileage'), 'car', ['mileage'], unique=False)
    op.create_index(op.f('ix_car_miles_until_oil_change'), 'car', ['miles_until_oil_change'], unique=False)
    op.create_index(op.f('ix_car_model'), 'car', ['model'], unique=False)
    op.create_index(op.f('ix_car_registration_date'), 'car', ['registration_date'], unique=False)
    op.create_index(op.f('ix_car_user'), 'car', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_user'), table_name='car')
    op.drop_index(op.f('ix_car_registration_date'), table_name='car')
    op.drop_index(op.f('ix_car_model'), table_name='car')
    op.drop_index(op.f('ix_car_miles_until_oil_change'), table_name='car')
    op.drop_index(op.f('ix_car_mileage'), table_name='car')
    op.drop_index(op.f('ix_car_make'), table_name='car')
    op.drop_index(op.f('ix_car_color'), table_name='car')
    op.drop_index(op.f('ix_car_car_vin'), table_name='car')
    op.drop_table('car')
    op.drop_index(op.f('ix_user_user'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_schedules_vehicle'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_user'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_status'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_mechanic'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_appointment_type'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_appointment_time'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_appointment_date'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_reviews_user'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_mechanic'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_comment'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_recommendations_user'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_Tire_rotations'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_Registration_update'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_Oil_change'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_Change_break'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_Car_Wash'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_mechanic__ratings_mechanic'), table_name='mechanic__ratings')
    op.drop_index(op.f('ix_mechanic__ratings_average'), table_name='mechanic__ratings')
    op.drop_table('mechanic__ratings')
    op.drop_index(op.f('ix_availability_user'), table_name='availability')
    op.drop_index(op.f('ix_availability_start_time'), table_name='availability')
    op.drop_index(op.f('ix_availability_end_time'), table_name='availability')
    op.drop_index(op.f('ix_availability_date'), table_name='availability')
    op.drop_table('availability')
    # ### end Alembic commands ###
