"""Fixing DB with roles

Revision ID: be19382eb39b
Revises: 
Create Date: 2019-11-11 14:52:35.920132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be19382eb39b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'urole')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('urole', sa.VARCHAR(length=80), nullable=True))
    # ### end Alembic commands ###
