"""empty message

Revision ID: fb5e23fb5b83
Revises: be19382eb39b
Create Date: 2019-11-12 08:38:10.484555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5e23fb5b83'
down_revision = 'be19382eb39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.drop_column('urole')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urole', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_role'))

    # ### end Alembic commands ###
